name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: http://download.h2os.com/5T/MP/OnePlus5THydrogen_43_OTA_065_all_2012030405_03dba2c095454647.zip
  ROM_NAME: OxygenOS
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements with XiaoxinSGSI setup script
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              git clone https://github.com/xiaoxindada/actions_build_SGSI.git setupp
              cd setupp/bin
              sudo bash ./setup.sh
              
       - name: Download Stock Rom & Generate GSI
         run: |
             cd $GITHUB_WORKSPACE/ErfanGSIs
             sudo bash ./url2GSI.sh -c -b $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              7za a -t7z -r final/GSI.7z ./*
              du -sh final/GSI.7z
              
       - name: Install rclone #安装rclone
         run: curl https://rclone.org/install.sh | sudo bash

       - name: Unzip config #解压配置文件
         run: |
          mkdir -p ~/.config/rclone/
          unzip -P ${{ secrets.PASSWD }} rclone.zip -d ~/.config/rclone/

       - name: Run rclone #运行rclone
         run: |
          
          # 更改时区

          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

          # 列出文件(此处不展示)

          echo "列出文件(此处不展示)"
          cd $GITHUB_WORKSPACE/ErfanGSIs/output
          rclone move final/GSI.7z e5:/od/

       - name: Zip config #打包配置文件
         run: zip -P ${{ secrets.PASSWD }} rclone.zip -j ~/.config/rclone/rclone.conf

       - name: Commit config #提交配置文件
         run: |
          git config --global user.email "2870926414@qq.com"
          git config --global user.name "SakuraH-LY"
          git add .
          git commit -am "new rclone config"
         git push
              
